// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghtpxrzvghondpvyxoit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdodHB4cnp2Z2hvbmRwdnl4b2l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNDAyNzQsImV4cCI6MjA3MDYxNjI3NH0.6tIYuqWQKh-TgEFTUHe5_IMPuFlnqqTaElMpAZLybXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});